variable "region" {}
variable "zone" {}
variable "gcp_project" {}
variable "credentials" {}
variable "network_name" {}
variable "subnet_name" {}
variable "subnet_cidr" {}
variable "k8s_workers_qty" {}
variable "k8s_controllers_qty" {}